# The title is the title of your Add-On
title: Custom Metadata
# The description will be shown above the form when activating the Add-On
description: enter which type of document data you would like to retrieve
# Type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
# Properties are the fields for your form
properties:
  # the key is the name of the variable that will be returned to your code
  ID:
    title: ID
    type: boolean

  Title:
    title: Title
    type: boolean

  Privacy Level:
    title: Privacy Level
    type: boolean

  Asset-Url:
    title: Asset-Url
    type: boolean

  Contributor:
    title: Contributor
    type: boolean

  Created at Date:
    title: Created at Date
    type: boolean

  Description:
    title: Description
    type: boolean

  Full Text Url:
    title: Full Text Url
    type: boolean

  Pdf Url:
    title: Pdf Url
    type: boolean

  Page Count:
    title: Page Count
    type: boolean

  Tags:
    title: Tags
    type: boolean

  Key Value Pairs:
    title: Key Value Pairs
    type: boolean


