# The title is the title of your Add-On
title: Custom Metadata
# The description will be shown above the form when activating the Add-On
description: enter which type of document data you would like to retrieve
# Type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the current search query
  - query
  # By the currently selected documents
  - selected
# Properties are the fields for your form
properties:
  # the key is the name of the variable that will be returned to your code
  choices:
    title: ID
    type: boolean

    title: Title
    type: boolean

    title: Privacy Level
    type: boolean

    title: Asset-Url
    type: boolean

    title: Contributor
    type: boolean

    title: Created at Date
    type: boolean

    title: Description
    type: boolean

    title: Full Text Url
    type: boolean

    title: Pdf Url
    type: boolean

    title: Page Count
    type: boolean

    title: Tags
    type: boolean

    title: Key Value Pairs
    type: boolean


